export const questions = [
  {
    question: `Do we have VA’s who can provide 24/7 support?`,
    answer: `Yes, we do.`,
  },
  {
    question: `How Do We Communicate?`,
    answer: `We have a state of the art Project Management tool that you will access when you start with us.

The portal will allow you to assign tasks, start discussions, upload files, and fully integrates with your email for quick communication.

We can help you determine a cost effective way to gain your valuable time back so you can spend it on what’s important to you ; whether that’s refocusing on growing your business, or spending more time with your family.`,
  },
  {
    question: `Lorem ipsum dolor sit amet.`,
    answer: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum dicta id possimus ratione. Quibusdam ea deleniti officia quae ex quaerat nisi error quisquam dolorem?`,
  },
  {
    question: `Lorem ipsum dolor sit amet consectetur.`,
    answer: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum dicta id possimus ratione. Quibusdam ea deleniti officia quae ex quaerat nisi error quisquam dolorem?`,
  },
  {
    question: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum.`,
    answer: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum dicta id possimus ratione. Quibusdam ea deleniti officia quae ex quaerat nisi error quisquam dolorem?`,
  },
];
// interface teamsProps {
//   id: number;
//   name: string;
//   role: string;
//   img: string;
//   expertise?: string[];
//   tools?: string[];
// }
export const teams = [
  {
    id: 0,
    name: "Joseph M.",
    role: "Vice-President",
    img: "/joseph2.jpg",
    expertise: [
      "Good English Communication ",
      "Flexibility",
      "Active Listening Skills",
      "Organizational Skills ",
      "Time Management",
      "Writing Skills",
      "Documenting Skills",
    ],
    tools: [
      "Linkedin Sales Navigator",
      "Expandi",
      "Instantly",
      "QuickMail",
      "Toggl ",
      "Outlook and Google Calendar",
      "Google Suites",
      "Microsoft Suites",
      "Asana",
      "Monday",
      "Trello",
      "ChatGPT",
      "QuillBot",
      "Audacity",
      "Slack",
      "LastPass",
      "Appointmentlet",
      "META for FB and IG",
      "Canva",
      "Capcut",
      "Jobber",
      "Engagebay",
      "Mailchimp",
      "Clearout",
      "Rephonic, PR Pitches",
    ],
  },
  {
    id: 1,
    name: "Mark E.",
    role: "Director of Web Development",
    img: "/mjestacio2.jpg",
    expertise: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "SCSS/Sass",
      "Tailwind CSS",
      "React",
      "NextJs",
      "Svelte",
      "Nodejs",
      "Elementor",
      "Webflow",
    ],
    tools: [
      "Adobe Photoshop",
      "Canva",
      "Elementor",
      "Figma",
      "Visual Studio Code",
      "Git",
      "Github",
      "Supabase",
      "Stripe",
      "Firebase",
      "Resend",
    ],
  },
  {
    id: 2,
    name: " Liam G.",
    role: "Marketing Specialist/Team Lead",
    img: "/liam.jpg",
    expertise: [
      "Administrative Support",
      "Data Management",
      "Records Analysis",
      "Appointment Scheduling",
      "Email and Calendar Mgt",
      "Content Planning and Scheduling",
      "Social Media Management and Analytics",
      "Graphic Design",
      "Audience Research ",
      "Community Engagement ",
      "Search engine optimization ",
      "Lead Generation",
    ],
    tools: [
      "Canva",
      "Capcut",
      "Adobe Photoshop",
      "Discord",
      "Skype",
      "Zoom",
      "Microsoft Teams",
      "Google Suites",
      "Slack",
      "Loomly",
      "Calendly",
      "Meta Business Suite",
      "Monday",
      "Asana",
      "Notion",
      "Basecamp",
      "ChatGPT",
      "Copy AI",
      "Jasper AI",
      "Wordpress",
      "GoDaddy",
      "Hubspot",
      "Active Campaign",
    ],
  },
  {
    id: 3,
    name: "Jon",
    role: "Project Manager",
    img: "/jon.jpg",
    expertise: [
      "Relationship Management",
      "Communications",
      "Project Management Skills",
      "Business Development",
      "Problem-Solving and Negotiation",
      "Sales",
      "Lead Generation",
      "prospecting",
      "Client Success management",
      "Appointment setting",
    ],
    tools: [
      "Linkedin Sales Navigator",
      "Motion",
      "Google workspace",
      "Instantly",
      "Apollo ",
      "ZoomInfo",
      "Clickup",
      "Monday",
      "Salesforce",
      "Hubspot",
      "Calendly",
      "Canva",
      "Gemini",
      "ChatGPT",
      "Mailchimp",
      "Sonido",
      "Ringcentral",
      "META",
      "Go High Level",
      "Snov",
      "HeyReach",
      "HubSpot",
    ],
  },

  {
    id: 4,
    name: "Princess L.",
    role: "E-commerce Specialist",
    img: "/princess.jpg",
    expertise: [
      "E-Coomerse Store Management ",
      "Bookkeeping",
      "Customer Support",
      "Email Management",
      "Product Research",
    ],
    tools: ["To Follow"],
  },

  {
    id: 5,
    name: "Amelia L.",
    role: "Creative Director",
    img: "/amelia.jpg",
    expertise: [
      "General Virtual Assistance",
      "Travel Management",
      "Inbox Management",
      "Calendar Management",
      "Meeting Management",
      "Social Media Management",
      "Creating Social Media Graphics (Canva)",
      "Video Editing (Camtasia)",
      "Search Engine Optimization",
      "Amazon Product Sourcing (Canada)",
      "Podcast Management",
    ],
    tools: [
      "Canva",
      "Google Workspace",
      "Microsoft Office",
      "Calendly",
      "Hootsuite ",
      "Late",
      "Facebook Meta",
      "Loom",
      "Zoom",
      "Asana",
      "Trello",
      "Notion",
      "Discord",
      "Slack",
      "Whatsapp",
      "Grammarly",
      "Chat gpt",
      "Camtasia",
      "Capcut",
    ],
  },
  {
    id: 6,
    name: "Shaina M.",
    role: "Communications Director",
    img: "/shaina2.jpg",
    expertise: [
      "Good English Communication ",
      "Organizational skills",
      "Time Management ",
      "Detail Oriented",
      "Computer Skills",
      "Social Media Management",
      "Leadership",
    ],
    tools: [
      "Profi",
      "Instantly",
      "Canva",
      "Microsoft Office",
      "Namecheap",
      "Admin Console",
      "Blue host",
      "Mashore Method",
      "Google Calendar ",
      "Outlook Calendar ",
      "Calendly",
      "Expandi",
      "Photoshop",
      "Filmora",
      "HubSpot ",
      "Quickbooks",
      "Chat GPT",
      "Meta Management",
      "Slack",
      "Capcut",
      "Lastpass",
      "Forecastr",
      "Skyslope",
      "Top Production ",
      "MLS",
      "LinkedIn ",
      "LinkedIn Sales Navigator ",
      "Google Workspace ",
      "Loom ",
      "Zoom",
      "Ring Central ",
      "Air Table",
      "Redfin",
      "Zillow",
      "Apollo",
      "Go Daddy",
      "ControlQore",
    ],
  },
  {
    id: 7,
    name: "Islay R.",
    role: "President",
    img: "/islay.jpg",
    expertise: [
      "Music Production and Performance",
      "Brainstorming",
      "Copywriting",
      "Scriptwriting",
      "Video Editing",
      "Logo design",
      "Drag and drop web design",
      "Team Building",
      "Motivator",
      "Collaborator",
      "Executioner",
      "Boss Man",
      "King Maker",
    ],
    tools: [
      "Audio Evolution",
      "Logic Pro",
      "Sibelius",
      "SimpleMind",
      "ChatGPT ",
      "Sony Vegas pro",
      "Lumafusion",
      "Canva",
      "Notability",
      "Blocs",
      "Squarespace",
      "MS Office",
      "Google Workspace",
      "iOS Numbers",
    ],
  },
];
// Industry Section Data
export const industryList = [
  {
    industry: "Healthcare",
    content: [
      "Scheduling patient appointments",
      "Medical billing and coding",
      "Managing medical records",
      "Customer support (answering common queries)",
      "Insurance claims processing",
      "Prescription refill management",
    ],
  },
  {
    industry: "Real Estate",
    content: [
      "Lead generation and follow-up",
      "Property listing management",
      "Appointment scheduling and calendar management",
      "Handling buyer and renter inquiries",
      "Market research and data entry",
      "Transaction coordination",
    ],
  },
  {
    industry: "Finance & Accounting",
    content: [
      "Bookkeeping and financial reporting",
      "Accounts payable/receivable management",
      "Tax preparation assistance",
      "Payroll processing",
      "Invoice creation and follow-up",
      "Financial data entry and analysis",
    ],
  },
  {
    industry: "E-commerce",
    content: [
      "Product listing management",
      "Order processing and fulfillment",
      "Customer service (responding to inquiries and complaints)",
      "Inventory management",
      "Marketing support (email campaigns, social media, SEO)",
      "Product research and supplier communication",
    ],
  },
  {
    industry: "Legal",
    content: [
      "Document preparation and review",
      "Legal research and case law analysis",
      "Scheduling client meetings and court dates",
      "Client communication and follow-up",
      "Billing and invoicing support",
      "Contract management",
    ],
  },
  {
    industry: "Information Technology (IT)",
    content: [
      "Technical support for customers",
      "Data entry and database management",
      "Project management support",
      "Software testing and bug tracking",
      "IT helpdesk support",
      "Documenting processes and procedures",
    ],
  },
  {
    industry: "Marketing & Advertising",
    content: [
      "Social media management and content creation",
      "SEO and website optimization",
      "Email marketing campaigns",
      "Market research and data analysis",
      "Advertising campaign management",
      "Event planning and coordination",
    ],
  },
  {
    industry: "Consulting",
    content: [
      "Client scheduling and communication",
      "Report writing and presentation preparation",
      "Data analysis and research",
      "Project management assistance",
      "Travel arrangements",
      "Client onboarding and follow-up",
    ],
  },
  {
    industry: "Hospitality",
    content: [
      "Reservation management",
      "Customer service support (handling inquiries and complaints)",
      "Event planning assistance",
      "Social media management and promotion",
      "Travel booking and itinerary management",
      "Administrative tasks (e.g., invoicing, data entry)",
    ],
  },
  {
    industry: "Travel & Tourism",
    content: [
      "Travel booking and itinerary planning",
      "Customer support for travelers",
      "Managing reservations and bookings",
      "Research on travel destinations",
      "Marketing and promotional activities",
      "Handling travel logistics and coordination",
    ],
  },
  {
    industry: "Retail",
    content: [
      "Customer service and order management",
      "Inventory tracking and management",
      "Handling returns and exchanges",
      "Marketing and promotional activities",
      "Product research and sourcing",
      "Data entry and administrative tasks",
    ],
  },
  {
    industry: "Non-Profit Organizations",
    content: [
      "Donor communication and fundraising support",
      "Event planning and coordination",
      "Volunteer management",
      "Social media and content creation",
      "Grant research and application preparation",
      "Managing donor databases",
    ],
  },
  {
    industry: "Entrepreneurs & Startups",
    content: [
      "Administrative support (e.g., email, calendar management)",
      "Market research and competitor analysis",
      "Social media and marketing activities",
      "Project management and task delegation",
      "Customer support and lead generation",
      "Product development research",
    ],
  },
  {
    industry: "Entertainment",
    content: [
      "Talent scheduling and management",
      "Social media management and fan engagement",
      "Event planning and coordination",
      "Marketing and promotional support",
      "Travel arrangements for shows and tours",
      "Managing communication with press and stakeholders",
    ],
  },
  {
    industry: "Publishing",
    content: [
      "Content editing and proofreading",
      "Author scheduling and communication",
      "Book promotion and marketing campaigns",
      "Digital book sales and distribution management",
      "Reader inquiries and customer support",
      "Blog and website management",
    ],
  },
  {
    industry: "Human Resources (HR)",
    content: [
      "Recruitment and candidate screening",
      "Employee onboarding and offboarding",
      "Payroll processing and benefits administration",
      "Employee engagement and communication",
      "Compliance tracking and documentation",
      "HR policy creation and updates",
    ],
  },
  {
    industry: "Insurance",
    content: [
      "Policy management and renewals",
      "Claims processing support",
      "Customer service for policyholders",
      "Data entry and documentation",
      "Lead generation and follow-up",
      "Appointment scheduling",
    ],
  },
  {
    industry: "Architecture & Engineering",
    content: [
      "Project management and coordination",
      "Client communication and scheduling",
      "Research and data collection for projects",
      "Document preparation and revision",
      "Vendor management",
      "Budget tracking and reporting",
    ],
  },
  {
    industry: "Manufacturing",
    content: [
      "Inventory tracking and management",
      "Order processing and fulfillment",
      "Vendor communication and management",
      "Data entry and administrative support",
      "Customer service and order inquiries",
      "Logistics and supply chain coordination",
    ],
  },
  {
    industry: "Transportation & Logistics",
    content: [
      "Dispatch coordination and communication",
      "Customer service for shipment tracking",
      "Route planning and scheduling",
      "Data entry and document management",
      "Invoice processing and billing",
      "Driver and vehicle management support",
    ],
  },
  {
    industry: "Event Planning",
    content: [
      "Venue research and booking",
      "Vendor communication and management",
      "Guest list management and RSVP tracking",
      "Budget tracking and reporting",
      "Marketing and promotional activities",
      "Logistics coordination",
    ],
  },
  {
    industry: "Construction",
    content: [
      "Project management support",
      "Vendor communication and scheduling",
      "Document preparation (permits, contracts)",
      "Customer communication and updates",
      "Budget and expense tracking",
      "Administrative tasks (e.g., data entry, invoicing)",
    ],
  },
  {
    industry: "Agriculture",
    content: [
      "Farm inventory management",
      "Customer communication (e.g., distributors, suppliers)",
      "Data entry and reporting (crop yields, sales)",
      "Scheduling of labor and equipment",
      "Marketing and social media management",
      "Vendor management",
    ],
  },
  {
    industry: "Media & Communications",
    content: [
      "Social media management",
      "PR outreach and communication",
      "Content creation and scheduling",
      "Market research and audience analysis",
      "Podcast and video production support",
      "Email marketing and campaign management",
    ],
  },
  {
    industry: "Automotive",
    content: [
      "Appointment scheduling for services",
      "Customer support and communication",
      "Inventory management for dealerships",
      "Marketing and promotional activities",
      "Data entry and record management",
      "Vendor communication and management",
    ],
  },
  {
    industry: "Telecommunications",
    content: [
      "Customer support and troubleshooting",
      "Appointment scheduling for installation/repair",
      "Data entry and management",
      "Marketing and customer retention activities",
      "Technical support assistance",
      "Billing and payment management",
    ],
  },
  {
    industry: "Fashion & Apparel",
    content: [
      "Product listing management",
      "Inventory tracking and management",
      "Customer support (returns, exchanges, inquiries)",
      "Social media and influencer engagement",
      "Order processing and fulfillment",
      "Marketing and promotional campaigns",
    ],
  },
  {
    industry: "Energy & Utilities",
    content: [
      "Customer service and support",
      "Data entry and management (usage, billing)",
      "Scheduling of service appointments",
      "Market research and analysis",
      "Billing and invoicing support",
      "Technical support for customers",
    ],
  },
  {
    industry: "Security",
    content: [
      "Monitoring and alarm response coordination",
      "Scheduling and dispatching security personnel",
      "Customer communication and support",
      "Report writing and data entry",
      "Vendor and equipment management",
      "Invoice processing and payment tracking",
    ],
  },
  {
    industry: "Food & Beverage",
    content: [
      "Reservation and event management",
      "Customer service (handling orders, complaints)",
      "Inventory tracking and supplier communication",
      "Social media and marketing campaigns",
      "Online order processing and management",
      "Data entry and administrative tasks",
    ],
  },
  {
    industry: "Fitness & Wellness",
    content: [
      "Appointment scheduling for clients",
      "Client communication and follow-up",
      "Social media and content creation",
      "Marketing and promotional activities",
      "Managing online classes and course content",
      "Billing and membership management",
    ],
  },
  {
    industry: "Art & Design",
    content: [
      "Client communication and scheduling",
      "Project management and coordination",
      "Social media management and promotion",
      "Market research and trend analysis",
      "Invoice and payment processing",
      "Event planning and gallery coordination",
    ],
  },
  {
    industry: "Gaming",
    content: [
      "Customer support and community management",
      "Game testing and bug reporting",
      "Social media and marketing campaigns",
      "Event planning and coordination (e.g., tournaments)",
      "Data entry and analysis for game metrics",
      "Content creation and management",
    ],
  },
  {
    industry: "Pharmaceuticals",
    content: [
      "Research assistance and data management",
      "Appointment scheduling with healthcare providers",
      "Customer support for pharmaceutical queries",
      "Document preparation (clinical trial data, reports)",
      "Supply chain and inventory tracking",
      "Marketing and compliance support",
    ],
  },
  {
    industry: "Pet Care",
    content: [
      "Appointment scheduling for grooming, veterinary services",
      "Customer communication and follow-up",
      "Inventory tracking and order management",
      "Marketing and social media promotion",
      "Administrative support (e.g., invoicing, data entry)",
      "Event planning (e.g., pet adoption events)",
    ],
  },
  {
    industry: "Government & Public Sector",
    content: ["Scheduling and communication with stakeholders"],
  },
];
