export const questions = [
  {
    question: `Do we have VA’s who can provide 24/7 support?`,
    answer: `Yes, we do.`,
  },
  {
    question: `How Do We Communicate?`,
    answer: `We have a state of the art Project Management tool that you will access when you start with us.

The portal will allow you to assign tasks, start discussions, upload files, and fully integrates with your email for quick communication.

We can help you determine a cost effective way to gain your valuable time back so you can spend it on what’s important to you ; whether that’s refocusing on growing your business, or spending more time with your family.`,
  },
  {
    question: `Lorem ipsum dolor sit amet.`,
    answer: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum dicta id possimus ratione. Quibusdam ea deleniti officia quae ex quaerat nisi error quisquam dolorem?`,
  },
  {
    question: `Lorem ipsum dolor sit amet consectetur.`,
    answer: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum dicta id possimus ratione. Quibusdam ea deleniti officia quae ex quaerat nisi error quisquam dolorem?`,
  },
  {
    question: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum.`,
    answer: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum dicta id possimus ratione. Quibusdam ea deleniti officia quae ex quaerat nisi error quisquam dolorem?`,
  },
];
// interface teamsProps {
//   id: number;
//   name: string;
//   role: string;
//   img: string;
//   expertise?: string[];
//   tools?: string[];
// }
export const teams = [
  {
    id: 0,
    name: "Joseph M.",
    role: "Vice-President",
    img: "/joseph2.jpg",
    expertise: [
      "Good English Communication ",
      "Flexibility",
      "Active Listening Skills",
      "Organizational Skills ",
      "Time Management",
      "Writing Skills",
      "Documenting Skills",
    ],
    tools: [
      "Linkedin Sales Navigator",
      "Expandi",
      "Instantly",
      "QuickMail",
      "Toggl ",
      "Outlook and Google Calendar",
      "Google Suites",
      "Microsoft Suites",
      "Asana",
      "Monday",
      "Trello",
      "ChatGPT",
      "QuillBot",
      "Audacity",
      "Slack",
      "LastPass",
      "Appointmentlet",
      "META for FB and IG",
      "Canva",
      "Capcut",
      "Jobber",
      "Engagebay",
      "Mailchimp",
      "Clearout",
      "Rephonic, PR Pitches",
    ],
  },
  {
    id: 1,
    name: "Mark E.",
    role: "Director of Web Development",
    img: "/mjestacio2.jpg",
    expertise: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "SCSS/Sass",
      "Tailwind CSS",
      "React",
      "NextJs",
      "Svelte",
      "Nodejs",
      "Elementor",
      "Webflow",
    ],
    tools: [
      "Adobe Photoshop",
      "Canva",
      "Elementor",
      "Figma",
      "Visual Studio Code",
      "Git",
      "Github",
      "Supabase",
      "Stripe",
      "Firebase",
      "Resend",
    ],
  },
  {
    id: 2,
    name: " Liam G.",
    role: "Marketing Specialist/Team Lead",
    img: "/liam.jpg",
    expertise: [
      "Administrative Support",
      "Data Management",
      "Records Analysis",
      "Appointment Scheduling",
      "Email and Calendar Mgt",
      "Content Planning and Scheduling",
      "Social Media Management and Analytics",
      "Graphic Design",
      "Audience Research ",
      "Community Engagement ",
      "Search engine optimization ",
      "Lead Generation",
    ],
    tools: [
      "Canva",
      "Capcut",
      "Adobe Photoshop",
      "Discord",
      "Skype",
      "Zoom",
      "Microsoft Teams",
      "Google Suites",
      "Slack",
      "Loomly",
      "Calendly",
      "Meta Business Suite",
      "Monday",
      "Asana",
      "Notion",
      "Basecamp",
      "ChatGPT",
      "Copy AI",
      "Jasper AI",
      "Wordpress",
      "GoDaddy",
      "Hubspot",
      "Active Campaign",
    ],
  },
  {
    id: 3,
    name: "Jon",
    role: "Project Manager",
    img: "/jon.jpg",
    expertise: [
      "Relationship Management",
      "Communications",
      "Project Management Skills",
      "Business Development",
      "Problem-Solving and Negotiation",
      "Sales",
      "Lead Generation",
      "prospecting",
      "Client Success management",
      "Appointment setting",
    ],
    tools: [
      "Linkedin Sales Navigator",
      "Motion",
      "Google workspace",
      "Instantly",
      "Apollo ",
      "ZoomInfo",
      "Clickup",
      "Monday",
      "Salesforce",
      "Hubspot",
      "Calendly",
      "Canva",
      "Gemini",
      "ChatGPT",
      "Mailchimp",
      "Sonido",
      "Ringcentral",
      "META",
      "Go High Level",
      "Snov",
      "HeyReach",
      "HubSpot",
    ],
  },

  {
    id: 4,
    name: "Princess L.",
    role: "E-commerce Specialist",
    img: "/princess.jpg",
    expertise: [
      "E-Coomerse Store Management ",
      "Bookkeeping",
      "Customer Support",
      "Email Management",
      "Product Research",
    ],
    tools: ["To Follow"],
  },

  {
    id: 5,
    name: "Amelia L.",
    role: "Creative Director",
    img: "/amelia.jpg",
    expertise: [
      "General Virtual Assistance",
      "Travel Management",
      "Inbox Management",
      "Calendar Management",
      "Meeting Management",
      "Social Media Management",
      "Creating Social Media Graphics (Canva)",
      "Video Editing (Camtasia)",
      "Search Engine Optimization",
      "Amazon Product Sourcing (Canada)",
      "Podcast Management",
    ],
    tools: [
      "Canva",
      "Google Workspace",
      "Microsoft Office",
      "Calendly",
      "Hootsuite ",
      "Late",
      "Facebook Meta",
      "Loom",
      "Zoom",
      "Asana",
      "Trello",
      "Notion",
      "Discord",
      "Slack",
      "Whatsapp",
      "Grammarly",
      "Chat gpt",
      "Camtasia",
      "Capcut",
    ],
  },
  {
    id: 6,
    name: "Shaina M.",
    role: "Communications Director",
    img: "/shaina2.jpg",
    expertise: [
      "Good English Communication ",
      "Organizational skills",
      "Time Management ",
      "Detail Oriented",
      "Computer Skills",
      "Social Media Management",
      "Leadership",
    ],
    tools: [
      "Profi",
      "Instantly",
      "Canva",
      "Microsoft Office",
      "Namecheap",
      "Admin Console",
      "Blue host",
      "Mashore Method",
      "Google Calendar ",
      "Outlook Calendar ",
      "Calendly",
      "Expandi",
      "Photoshop",
      "Filmora",
      "HubSpot ",
      "Quickbooks",
      "Chat GPT",
      "Meta Management",
      "Slack",
      "Capcut",
      "Lastpass",
      "Forecastr",
      "Skyslope",
      "Top Production ",
      "MLS",
      "LinkedIn ",
      "LinkedIn Sales Navigator ",
      "Google Workspace ",
      "Loom ",
      "Zoom",
      "Ring Central ",
      "Air Table",
      "Redfin",
      "Zillow",
      "Apollo",
      "Go Daddy",
      "ControlQore",
    ],
  },
  {
    id: 7,
    name: "Islay R.",
    role: "President",
    img: "/islay.jpg",
    expertise: [
      "Music Production and Performance",
      "Brainstorming",
      "Copywriting",
      "Scriptwriting",
      "Video Editing",
      "Logo design",
      "Drag and drop web design",
      "Team Building",
      "Motivator",
      "Collaborator",
      "Executioner",
      "Boss Man",
      "King Maker",
    ],
    tools: [
      "Audio Evolution",
      "Logic Pro",
      "Sibelius",
      "SimpleMind",
      "ChatGPT ",
      "Sony Vegas pro",
      "Lumafusion",
      "Canva",
      "Notability",
      "Blocs",
      "Squarespace",
      "MS Office",
      "Google Workspace",
      "iOS Numbers",
    ],
  },
];
