import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { SpeedInsights } from "@vercel/speed-insights/next";

import LiveChat from "@/components/LiveChat";
import LiveChatv2 from "@/components/LiveChatv2";
import Script from "next/script";

//   subsets: ["latin"],
//   variable: "--font-montserrat",
// });
// const roboto = Roboto({
//   subsets: ["latin"],
//   variable: "--font-roboto",
//   weight: ["400", "500", "700"],
// });
// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   weight: ["400", "500", "600", "700"],
// });
export const metadata: Metadata = {
  title: "VirtualCrew.net",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="poppins">
        <Navbar />
        <Toaster
          position="top-center"
          toastOptions={{ duration: 3000 }}
        />
        {children}
        <Footer />
        <SpeedInsights />
        {/* <LiveChat /> */}

        {/* <LiveChatv2 /> */}
        <Script
          src="https://widgets.leadconnectorhq.com/loader.js"
          data-resources-url="https://widgets.leadconnectorhq.com/chat-widget/loader.js"
          data-widget-id="678f03c21b88777fd0648cb0"
        />
      </body>
    </html>
  );
}
